// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/kdmr-hero/Current.tsx": () => import("../components/mockups/kdmr-hero/Current.tsx"),
  "./components/mockups/kdmr-hero/VariantA.tsx": () => import("../components/mockups/kdmr-hero/VariantA.tsx"),
  "./components/mockups/kdmr-hero/VariantB.tsx": () => import("../components/mockups/kdmr-hero/VariantB.tsx"),
  "./components/mockups/kdmr-hero/VariantC.tsx": () => import("../components/mockups/kdmr-hero/VariantC.tsx")
};
